version: '3'
services:
  app:
    container_name: stretch-rest
    restart: always
    build: .
    ports: 
      - '80:5000'
    links:
      - mongo
    environment:
      - STRETCH_CONNECTION_STRING=mongodb://stretch-db:27017/
  mongo:
    container_name: stretch-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - '/usr/local/var/mongodb:/data/db'