version: '3'
services:
  app:
    container_name: stretch-rest
    build: ../api
    ports:
      - '8000:8000'
    links:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=mongodb://super:PASSWORD@mongo:27017/
      - ADMIN_USER_EMAIL=admin@stretchauto.com
      - ADMIN_USER_USERNAME=admin
      - ADMIN_USER_PASSWORD=test123
      - JWT_SECRET_KEY=ilovetostretch
      - JWT_REFRESH_SECRET_KEY=ilovetostretch2
      - PORT=8000
  mongo:
    container_name: stretch-db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=super
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db

volumes:
  db-data:
