version: '3'
services:
  app:
    container_name: stretch-rest
    restart: always
    build: .
    ports: 
      - '80:5000'
    links:
      - mongo
    environment:
      - STRETCH_CONNECTION_STRING=mongodb://admin:PASSWORD@stretch-db:27017/
      - ADMIN_EMAIL=EMAIL
      - ADMIN_USERNAME=USERNAME
      - ADMIN_PASSWORD=PASSWORD
      - SALT_ROUNDS=ROUNDS
  mongo:
    container_name: stretch-db
    image: mongo
    command: [--auth]
    ports:
      - '27017:27017'
    volumes:
      - '/data/db:/data/db'
      - '/etc:/etc'