version: '3'
services:
  app:
    container_name: stretch-rest
    restart: always
    build: .
    ports: 
      - '80:80'
      - '443:443'
    links:
      - mongo
    environment:
      - STRETCH_CONNECTION_STRING=mongodb://super:PASSWORD@mongo:27017/
      - ADMIN_EMAIL=EMAIL
      - ADMIN_USERNAME=USERNAME
      - ADMIN_PASSWORD=PASSWORD
      - JWT_SECRET_KEY=SECRET
      - JWT_REFRESH_SECRET_KEY=SECRET
      - PRODUCTION=FALSE
  mongo:
    container_name: stretch-db
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=super
      - MONGO_INITDB_ROOT_PASSWORD=PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - '/data/db:/data/db'